Problem 1

In [11]:
import numpy as np
from scipy.spatial import ConvexHull

In [2]:
def generate_random_vectors(N):
    """
    Generates N independent 3D random vectors.
    - The first two coordinates follow an exponential distribution with parameter 1.
    - The third coordinate follows a standard normal distribution.
    """
    # First two coordinates: exponential distribution with lambda=1
    coord1 = np.random.exponential(scale=1, size=N)
    coord2 = np.random.exponential(scale=1, size=N)
    
    # Third coordinate: standard normal distribution
    coord3 = np.random.normal(loc=0, scale=1, size=N)
    
    # Combine into a 3D array of shape (N, 3)
    vectors = np.vstack((coord1, coord2, coord3)).T
    return vectors


In [15]:
N = 5  # Number of vectors
random_vectors = generate_random_vectors(N)
print("Generated Random Vectors:")
print(random_vectors)

Generated Random Vectors:
[[4.53464713 1.55674392 1.62471285]
 [0.66954061 1.33048193 0.61077981]
 [2.89768564 0.55935454 0.53435455]
 [1.74776186 2.85750174 0.08089001]
 [0.61237326 1.99812632 0.75655841]]


Problem 2

In [12]:
def find_separating_vector(vectors):
    """
    Implements Kozinec's algorithm to find the separating vector for
    the convex hull of the input 3D vectors.
    - The function identifies separating planes by using the convex hull.
    """
    # Compute the convex hull of the input vectors
    hull = ConvexHull(vectors)
    
    # Extract the plane equations from the convex hull
    # Each equation is of the form Ax + By + Cz + D = 0
    separating_vectors = hull.equations[:, :-1]  # Extract only (A, B, C) from the equations
    return separating_vectors


In [16]:
separating_vectors = find_separating_vector(random_vectors)
print("\nSeparating Vectors (Normals to the Convex Hull Facets):")
print(separating_vectors)


Separating Vectors (Normals to the Convex Hull Facets):
[[-0.08401964  0.68212098  0.72639636]
 [ 0.51408637  0.08889807 -0.85311918]
 [-0.23472236 -0.22650337  0.94530505]
 [-0.1742496  -0.58219566  0.79415697]
 [-0.57643259  0.12689972 -0.80723103]
 [-0.11924281 -0.2492989  -0.96105734]]
